server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-1snop47m.sql.tencentcdb.com:27854/HuAnX?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Hongkong
    username: root
    password: RTAsZv961MUT6
  mvc:
    view:
      suffix: .html
      prefix: /
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #wx:
  #小程序
#  appId: wx5745b3f0a911e8d8
#  secret: 9a4e5d01d729f1b9951b7d37a3375da0

# 日志
logging:
  level:
    mybatis: DEBUG
    com.baomidou.mybatis plus: DEBUG
